In [1]:
import numpy as np
import scipy.stats
import sklearn.datasets

In [2]:
N = 100
D = 2
K = 5

In [3]:
U0 = np.random.random((K,D))
V0 = np.zeros((K,D,D))
for i in range(K):
        V0[i] = sklearn.datasets.make_spd_matrix(D)
Z0 = np.random.random((K,))
Z0 = Z0/np.sum(Z0)

In [4]:
V0.shape

(5, 2, 2)

In [5]:
X = np.random.random((N,D))

In [6]:
Rnk = np.zeros((N,K))
Uk = U0
Ek = V0
PIk = Z0
Prev = -np.inf
epsilon = 1e-3
for _ in range(250):
    for i in range(N):
        Sum = 0
        for j in range(K):
            Rnk[i,j] = scipy.stats.multivariate_normal.pdf(X[i],Uk[j], Ek[j]) * PIk[j]
            Sum += Rnk[i,j]
        Rnk[i]=Rnk[i]/Sum
        
    Nk = np.sum(Rnk , axis = 0).reshape(-1,1)
    
    Uk = np.zeros((K,D))
    for j in range(K):
        Uk[j] = np.sum(Rnk[:,j:j+1]*X , axis = 0)
    Uk=Uk/Nk

    Ek = np.zeros((K,D,D))
    for i in range(N):
        for j in range(K):
            Ek[j] += Rnk[i,j:j+1]*(np.dot((X[i]-Uk[j]).reshape(D,1) , (X[i]-Uk[j]).reshape(1,D) ))
    Ek/=Nk.reshape(-1,1,1)

    PIk = Nk/N
    
    
    L = 0
        
    for i in range(N):
            Sum = 0
            for j in range(K):
                Sum += PIk[j]*scipy.stats.multivariate_normal.pdf(X[i],Uk[j], Ek[j])
            L += np.log(Sum)
        
    print("Log likelihood : ", L)
    if(np.abs(L - Prev) < epsilon):
        break
    else:
        Prev = L
    print("Mu_k :" , Uk)
    print("E_k :" , Ek)
    print("Pi_k :" , PIk)
        

Log likelihood :  [-40.13256599]
Mu_k : [[0.47756622 0.50478444]
 [0.45805155 0.47929377]
 [0.44955518 0.49296572]
 [0.4688137  0.55620886]
 [0.47511671 0.51189409]]
E_k : [[[0.08523286 0.00157972]
  [0.00157972 0.08872135]]

 [[0.08521772 0.00659102]
  [0.00659102 0.08631952]]

 [[0.08542862 0.00608031]
  [0.00608031 0.0917153 ]]

 [[0.08686692 0.00681488]
  [0.00681488 0.09051121]]

 [[0.08603867 0.00455838]
  [0.00455838 0.0892613 ]]]
Pi_k : [[0.22421493]
 [0.19578541]
 [0.17248282]
 [0.07707099]
 [0.33044585]]
Log likelihood :  [-40.12653517]
Mu_k : [[0.47737439 0.50504767]
 [0.45805273 0.47848816]
 [0.44952857 0.49338224]
 [0.46909719 0.55582062]
 [0.47519255 0.51206603]]
E_k : [[[0.0857898  0.00134614]
  [0.00134614 0.08931704]]

 [[0.08497287 0.00708236]
  [0.00708236 0.08742256]]

 [[0.08485276 0.00598697]
  [0.00598697 0.09003489]]

 [[0.08667561 0.00640115]
  [0.00640115 0.08883786]]

 [[0.08615178 0.00456351]
  [0.00456351 0.08945815]]]
Pi_k : [[0.22422253]
 [0.19578922]
 [0

Log likelihood :  [-39.98462284]
Mu_k : [[0.47349148 0.51374011]
 [0.46288597 0.46118175]
 [0.44547402 0.49086286]
 [0.46967062 0.56584976]
 [0.47695235 0.51567828]]
E_k : [[[ 0.08580132 -0.01124026]
  [-0.01124026  0.09071237]]

 [[ 0.08563719  0.0248242 ]
  [ 0.0248242   0.08532682]]

 [[ 0.084004    0.00809681]
  [ 0.00809681  0.08871904]]

 [[ 0.0861671  -0.00101724]
  [-0.00101724  0.0875293 ]]

 [[ 0.08627892  0.00300898]
  [ 0.00300898  0.08962426]]]
Pi_k : [[0.22479744]
 [0.197757  ]
 [0.17161436]
 [0.07695738]
 [0.32887382]]
Log likelihood :  [-39.94238656]
Mu_k : [[0.47287203 0.51463959]
 [0.46410618 0.45899171]
 [0.44520139 0.49081576]
 [0.46902773 0.56714637]
 [0.47693488 0.51619113]]
E_k : [[[ 0.08573457 -0.0129874 ]
  [-0.0129874   0.0908346 ]]

 [[ 0.08578997  0.02745304]
  [ 0.02745304  0.08495064]]

 [[ 0.08397936  0.00825716]
  [ 0.00825716  0.08867971]]

 [[ 0.08609127 -0.00184999]
  [-0.00184999  0.08745257]]

 [[ 0.08626836  0.00272908]
  [ 0.00272908  0.08963042]]

Log likelihood :  [-36.44048942]
Mu_k : [[0.47889541 0.50223723]
 [0.51356997 0.44949393]
 [0.41600626 0.50349371]
 [0.43470268 0.59543289]
 [0.4519539  0.53290568]]
E_k : [[[ 0.08454899 -0.06800634]
  [-0.06800634  0.09467364]]

 [[ 0.09201014  0.0701212 ]
  [ 0.0701212   0.08522343]]

 [[ 0.07946075  0.01390476]
  [ 0.01390476  0.08627676]]

 [[ 0.0796098  -0.00216343]
  [-0.00216343  0.08187899]]

 [[ 0.08207073  0.00509462]
  [ 0.00509462  0.08705634]]]
Pi_k : [[0.23146824]
 [0.25829806]
 [0.15270849]
 [0.06873076]
 [0.28879445]]
Log likelihood :  [-35.90430016]
Mu_k : [[0.4827506  0.50129406]
 [0.51719251 0.44949876]
 [0.41087643 0.50393993]
 [0.43149939 0.59777848]
 [0.44753691 0.53447785]]
E_k : [[[ 0.0853418  -0.07281992]
  [-0.07281992  0.09591189]]

 [[ 0.09125334  0.06948773]
  [ 0.06948773  0.08475888]]

 [[ 0.07868184  0.01586573]
  [ 0.01586573  0.08593989]]

 [[ 0.07918294  0.00111038]
  [ 0.00111038  0.08111183]]

 [[ 0.08152001  0.0079482 ]
  [ 0.0079482   0.08656858]]

Log likelihood :  [-32.07656541]
Mu_k : [[0.49991841 0.5139541 ]
 [0.62065043 0.46222213]
 [0.26572668 0.45909993]
 [0.41297519 0.64696836]
 [0.39273008 0.53690241]]
E_k : [[[ 0.09466427 -0.09396756]
  [-0.09396756  0.10601942]]

 [[ 0.06269357  0.05298215]
  [ 0.05298215  0.07907867]]

 [[ 0.04278917  0.01424025]
  [ 0.01424025  0.08123739]]

 [[ 0.07608828  0.02876463]
  [ 0.02876463  0.0718227 ]]

 [[ 0.07377999  0.03173868]
  [ 0.03173868  0.08659297]]]
Pi_k : [[0.22946023]
 [0.3000415 ]
 [0.15379505]
 [0.06181776]
 [0.25488547]]
Log likelihood :  [-31.31247577]
Mu_k : [[0.50247421 0.51154702]
 [0.63199718 0.46770737]
 [0.24254605 0.45016476]
 [0.41891015 0.65738663]
 [0.39224141 0.53758841]]
E_k : [[[ 0.09459167 -0.09396014]
  [-0.09396014  0.10600682]]

 [[ 0.05882249  0.05107159]
  [ 0.05107159  0.07885785]]

 [[ 0.03516738  0.0114975 ]
  [ 0.0114975   0.08040904]]

 [[ 0.07552151  0.0289306 ]
  [ 0.0289306   0.07010777]]

 [[ 0.07276781  0.03267429]
  [ 0.03267429  0.0872321 ]]

Log likelihood :  [-10.43205646]
Mu_k : [[0.63613834 0.35807322]
 [0.68101906 0.41276367]
 [0.1350853  0.55048612]
 [0.6357948  0.90173993]
 [0.36780769 0.36018018]]
E_k : [[[ 0.0635579  -0.05739756]
  [-0.05739756  0.06251187]]

 [[ 0.03626221  0.03713897]
  [ 0.03713897  0.05210721]]

 [[ 0.0075046   0.00863567]
  [ 0.00863567  0.09139219]]

 [[ 0.05565453  0.0024265 ]
  [ 0.0024265   0.00208187]]

 [[ 0.02660135  0.02036078]
  [ 0.02036078  0.04758062]]]
Pi_k : [[0.16981346]
 [0.24321049]
 [0.26666273]
 [0.14903093]
 [0.1712824 ]]
Log likelihood :  [-9.87520918]
Mu_k : [[0.64258687 0.35027781]
 [0.68865747 0.41604962]
 [0.13311728 0.55887571]
 [0.63653095 0.90168098]
 [0.36155406 0.35375418]]
E_k : [[[ 0.06165051 -0.05513744]
  [-0.05513744  0.05980128]]

 [[ 0.03436498  0.03640609]
  [ 0.03640609  0.05189089]]

 [[ 0.00732416  0.00925507]
  [ 0.00925507  0.0907753 ]]

 [[ 0.0553992   0.00244151]
  [ 0.00244151  0.00206836]]

 [[ 0.02453156  0.02021509]
  [ 0.02021509  0.04693073]]]

Log likelihood :  [-6.58352577]
Mu_k : [[0.74619887 0.23193099]
 [0.77242323 0.49231631]
 [0.12177264 0.59642271]
 [0.60248012 0.8960642 ]
 [0.3720719  0.34460729]]
E_k : [[[ 0.03478619 -0.02479232]
  [-0.02479232  0.02451208]]

 [[ 0.01748776  0.02488421]
  [ 0.02488421  0.04666786]]

 [[ 0.00622421  0.012043  ]
  [ 0.012043    0.08876804]]

 [[ 0.0603778   0.00449401]
  [ 0.00449401  0.00244493]]

 [[ 0.02234305  0.01486655]
  [ 0.01486655  0.0456846 ]]]
Pi_k : [[0.12186718]
 [0.18433789]
 [0.23915275]
 [0.15548165]
 [0.29916052]]
Log likelihood :  [-6.35246961]
Mu_k : [[0.75634853 0.2213887 ]
 [0.77628516 0.49703057]
 [0.12139917 0.59644331]
 [0.60055484 0.89582373]
 [0.37421423 0.34637358]]
E_k : [[[ 0.0321612  -0.0221228 ]
  [-0.0221228   0.02172748]]

 [[ 0.01683852  0.02421993]
  [ 0.02421993  0.04610607]]

 [[ 0.00618633  0.01207806]
  [ 0.01207806  0.08896836]]

 [[ 0.06060136  0.0045845 ]
  [ 0.0045845   0.00246502]]

 [[ 0.02250734  0.01450028]
  [ 0.01450028  0.04563708]]]


Log likelihood :  [-4.18208178]
Mu_k : [[0.868802   0.12081277]
 [0.79522676 0.51418753]
 [0.11785022 0.59674225]
 [0.58511614 0.89335841]
 [0.39806777 0.34738351]]
E_k : [[[ 0.01006311 -0.00287814]
  [-0.00287814  0.00364121]]

 [[ 0.0126716   0.01902142]
  [ 0.01902142  0.04078951]]

 [[ 0.00581084  0.01230597]
  [ 0.01230597  0.09088796]]

 [[ 0.06272462  0.00525733]
  [ 0.00525733  0.00266984]]

 [[ 0.02675741  0.01143235]
  [ 0.01143235  0.04236028]]]
Pi_k : [[0.06994067]
 [0.17548743]
 [0.2251828 ]
 [0.15954504]
 [0.36984406]]
Log likelihood :  [-4.17700529]
Mu_k : [[0.87011365 0.1202832 ]
 [0.79543928 0.51410523]
 [0.11779366 0.59707311]
 [0.58460711 0.89327102]
 [0.39826015 0.34726774]]
E_k : [[[ 0.00986135 -0.00279512]
  [-0.00279512  0.00361381]]

 [[ 0.01263174  0.01902481]
  [ 0.01902481  0.04091779]]

 [[ 0.00580241  0.01230625]
  [ 0.01230625  0.09085511]]

 [[ 0.06276901  0.00527702]
  [ 0.00527702  0.00267778]]

 [[ 0.0269193   0.01143379]
  [ 0.01143379  0.04231794]]]


In [7]:
Uk

array([[0.87296676, 0.11914512],
       [0.79664254, 0.51495792],
       [0.11756625, 0.59856345],
       [0.58261799, 0.89293199],
       [0.39871122, 0.34679012]])

In [8]:
Ek

array([[[ 0.00943903, -0.00262231],
        [-0.00262231,  0.00356382]],

       [[ 0.01246668,  0.01896659],
        [ 0.01896659,  0.04118521]],

       [[ 0.00576976,  0.01231108],
        [ 0.01231108,  0.09067502]],

       [[ 0.06291145,  0.00535691],
        [ 0.00535691,  0.00270843]],

       [[ 0.02749141,  0.01146571],
        [ 0.01146571,  0.04218088]]])

In [9]:
PIk

array([[0.06837492],
       [0.17449374],
       [0.22263016],
       [0.16011668],
       [0.37438451]])